"""added Weet

Revision ID: 236f6f2a04b0
Revises: 0e9eb9b30855
Create Date: 2021-02-15 10:51:25.476840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236f6f2a04b0'
down_revision = '0e9eb9b30855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weet')
    # ### end Alembic commands ###
