"""InvalidToken Added

Revision ID: 6f1b9a5361a8
Revises: 236f6f2a04b0
Create Date: 2021-02-17 12:08:28.538745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1b9a5361a8'
down_revision = '236f6f2a04b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invalid_tokens')
    # ### end Alembic commands ###
